name: prod

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            node -v
            cd ~/kino-list
            git pull
            npm install
            npm run build
            rm -r /var/www/dist
            mv ./dist /var/www/
